# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_count_sketch <- function(X, hv, gv, m) {
    .Call('_sketching_rcpp_count_sketch', PACKAGE = 'sketching', X, hv, gv, m)
}

